name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.4.0'
          cache: 'npm'
          
      - name: Install Dependencies
        run: npm ci
        
      - name: Install Angular CLI and GH Pages
        run: npm install -g @angular/cli angular-cli-ghpages
        
      - name: Build
        run: ng build --configuration production --base-href "https://gitlaws.github.io/PortfoliYOLO/"
        
      - name: Deploy to GitHub Pages
        run: npx angular-cli-ghpages --dir=dist/portfoli-yolo/browser --no-silent
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
